apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gch3ev39x-java-springboot
  janus-idp.io/tekton: gch3ev39x-java-springboot
  backstage.io/kubernetes-id: gch3ev39x-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gch3ev39x-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
